language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install pylint sympy numpy matplotlib"
# command to run tests
script:
  - "nosetests *.py"
notifications:
  email: false
